### ISSUE TITLE
Persist `Result`

### ISSUE THREAD

**Issue by turingcompl33t** [mlte-team/mlte#122]
We should add the ability to persist instances of `Result` across sessions. This makes the interface consistent with all other `mlte` types that support this functionality.

This capability is critical for allowing `mlte` to interoperate with other ML workflows. For instance, if users wish to communicate results in some manner _other_ than the MLTE report, then the ability to load all previously-collected `Result` instances provides this opportunity.

**Comment by turingcompl33t** [comment]
Update this issue to reference `Result` rather than `ValidationResult` to reflect rename.

**Comment by sebastian-echeverria** [comment]
Currently this can also be done through the ValidatedSpec, though in that case all results are put together. We would still have to evaluate if we want to persist results separately. One option is to add this ability, even if it is not used in the "standard" workflow.
