### ISSUE TITLE
Property Identification and Versioning

### ISSUE THREAD

**Issue by turingcompl33t** [mlte-team/mlte#13]
We need a more robust way to identify properties. So far, just have the property name. This is just a string, and there is no strict requirement of uniqueness. We need a way to attach a unique identifier to properties that remains constant over time.

On a related point, we need a mechanism to version properties. This will be additional metadata that is stored in the `Property` base class. This mechanism will also include a pre-commit (or pre-push?) hook that denies merges when a modified property does not have its version bumped.

**Comment by turingcompl33t** [comment]
Update: The version information should include a way to recover the commit hash for a version of the source that includes the referenced version of the property (measurement).

**Comment by sebastian-echeverria** [comment]
I do not think this is needed anymore. Properties are currently seen as more static entities that just define the name and definition of a property. As currently defined, there will not be "versions" of a Property, so no ids, no versions, and no metadata.

These requirements may have moved over to Results or some other entity, but they do not seem valid anymore.
