### ISSUE TITLE
Integrate Report Generation from `mlte-report`

### ISSUE THREAD

**Issue by turingcompl33t** [mlte-team/mlte#130]
Currently, report generation functionality is dispatched to the `mlte-report` component, which is deployed as a totally separate web service hosted on cloud resources. The decoupling is nice, but the fact that users have to "reach out" to the WAN in order to generate reports seems surprising and un-parsimonious. We should consider bundling the report generation as functionality within the package itself, such that it can be used offline.

**Comment by sebastian-echeverria** [comment]
As an updated, this is being done by rendering the report as part of the new UI frontend, in #179

**Comment by turingcompl33t** [comment]
Resolved by #289.
