### ISSUE TITLE
Rename `MeasurementMetadata`

### ISSUE THREAD

**Issue by turingcompl33t** [mlte-team/mlte#139]
The `MeasurementMetadata` object tracks information that is relevant to a particular element of evidence throughout its lifecycle. It is not specific to a `Measurement`, or it applies to more than just `Measurement`s. Accordingly, we should update the name to better indicate what it does.

**Comment by sebastian-echeverria** [comment]
This is addressed in #135

**Comment by turingcompl33t** [comment]
Resolved by #146.
