### ISSUE TITLE
Add method to load all Values from a store

### ISSUE THREAD

**Issue by sebastian-echeverria** [mlte-team/mlte#141]
Add a method, probably to the Value class, that allows you to load all Values from the current store into a list of Values. This may be complimentary to the work in #121 , as that could make this easier to do. Alternatively, this could be done without that change in a less elegant way.

**Comment by turingcompl33t** [comment]
Resolved by `Store` query functionality.

**Comment by sebastian-echeverria** [comment]
Even though this is possible by the Store query/filter/search_artifacts functionality, a substantial amount of code is needed to pull it off. It makes more sense to add a frontend, something like Value.load_all(), that underneath does the work to make it easier to load all Values from a Store.

Currently, partial code to do this would look something like this:

```
 with ManagedSession(session().store.session()) as handle:
    query = Query(filter=ArtifactTypeFilter(type=FilterType.TYPE, artifact_type=ArtifactType.VALUE))
    artifacts = handle.search_artifacts("ns", "IrisClassifier", "0.0.1")
    values = [Value.from_model(value_model) for value_model in artifacts]
```

However, this is not complete, as Value.from_model is specific for each Value subtype, so it wouldn't work in this simplified form. Furthermore, this should also work for external Value types extended by the user, so more work needs to be added to support that in a transparent way.
