### ISSUE TITLE
Add NegotiationCard entity

### ISSUE THREAD

**Issue by sebastian-echeverria** [mlte-team/mlte#142]
We want to start using and storing the NegotiationCard entity with MLTE. Add it as a first-level entity, that can be handled, stored and retrieved similarly to Spec.

Details of the Negotiation Card can be found here: https://github.com/mlte-team/mlte-framework/blob/master/framework/resources/process/negotiation_card.md

**Comment by turingcompl33t** [comment]
Closing as a duplicate of #151.
