### ISSUE TITLE
Design Report Integration with Negotiation Card

### ISSUE THREAD

**Issue by krmaffey** [mlte-team/mlte#161]
Determine content that goes from the negotiation card to the report and create a method to pull in those appropriate parts to the report

**Comment by turingcompl33t** [comment]
@krmaffey I am splitting this into two issues: design for this feature and implementation for this feature once the design is complete. We should probably talk about this soon.

**Comment by turingcompl33t** [comment]
@krmaffey @JennyNiemann I thought about this issue after our meeting yesterday. Here is my proposal:

- Under the hood, negotiation cards and reports remain distinct artifacts
- In the frontend, when a user opens the page to create a new report or edit an existing one, we supply an option to allow them to "populate from negotiation card"; this gives them a dropdown for all negotiation cards in the current context (namespace, model, version). When the users selects a negotiation card, we apply the negotiation card to report mapping to populate the fields in the report accordingly. When further edits are made to the report, in any field, these edits are **not** back-populated to the negotiation card.
- In the Python client (the `mlte` package) we provide similar functionality to populate a report from a negotiation card. I'll write something like:

```python
report = Report()
report.populate_from(NegotiationCard.load("my-card"))
```

This will behave similarly to the frontend in that further edits to the report do not impact the negotiation card used to populate it in any way.

If you are in agreement with this, I am going to write up some small issues to guide us to this solution. This will be the first feature that will involve all three of us working together.

**Comment by krmaffey** [comment]
I agree with this, @turingcompl33t! Tomorrow I'm going to start working through the chain of issues you've made and will comment accordingly. Unless @JennyNiemann disagrees, I recommend closing this issue and relying on the other ones you wrote that break up this process.
