### ISSUE TITLE
Add Logo to README

### ISSUE THREAD

**Issue by turingcompl33t** [mlte-team/mlte#163]
We should add the MLTE logo to the top-level project README.

**Comment by ishan-goyal-2003** [comment]
Hello,
Can you please tell me where can i find the logo and where in read me do i have to add the logo...
Thank you

**Comment by ep7481** [comment]
I can help if you assign to me.

**Comment by turingcompl33t** [comment]
Hi @ishan-goyal-2003 and @ep7481, thanks for your interest in this project! For this particular issue, I am going to leave it assigned to @krmaffey because she has access to the assets that are required to complete this task. However, I'll be updating this project with more good-first-issues in the near future. If you want to get involved, those will be good opportunities.

**Comment by turingcompl33t** [comment]
@krmaffey following what I have seen on other projects, I think we can just check all of our new assets into the repository under a top-level "assets" directory. The README can then just embed a link to the desired logo as a local filesystem path, and we will be able to reference the assets from other locations as well (e.g. embed a link to the Github raw assets in the UI rather than bundling the image with the site itself, I can work with Alex on this).

**Comment by turingcompl33t** [comment]
Resolved by [166](https://github.com/mlte-team/mlte/pull/166).
