### ISSUE TITLE
Report + Negotiation Card: Vet Current Negotiation Card Content

### ISSUE THREAD

**Issue by turingcompl33t** [mlte-team/mlte#225]
Review the current content of the negotiation card (best visible [here](https://github.com/mlte-team/mlte/blob/master/mlte/negotiation/model.py)). Determine if the content and organization are appropriate for the MLTE 0.2 release. If changes are required, notify @turingcompl33t to perform updates. If no updates are necessary, this issue can be resolved.

**Comment by krmaffey** [comment]
For the MLTE 0.2 release, I think this iteration of the negotiation card is a good starting point. I reviewed the negotiation card content as linked above and feel that it covers many of the challenges identified in our SEI team's mismatch [work](https://insights.sei.cmu.edu/blog/detecting-mismatches-machine-learning-systems/) as well as the challenges from Nadia/Grace/Christian's [paper](https://arxiv.org/pdf/2110.10234v4.pdf). There are certainly small changes we could make, but until we have user feedback I think that is not a good use of our time.

@turingcompl33t, feel free to close this issue as well as #226.

**Comment by turingcompl33t** [comment]
Roger @krmaffey, closing.
