### ISSUE TITLE
Report + Negotiation Card: Implement Mapping (Frontend)

### ISSUE THREAD

**Issue by turingcompl33t** [mlte-team/mlte#231]
#229 proposes a mapping between the fields of a negotiation card and the fields of a report. Once this mapping is implemented in the backend, we need to replicate it on the frontend such that we can populate a report from a selected negotiation card.

Proposed elements for this UI include:

- Select existing report artifact or "create new" option
- On report edit page, option is available to "populate from negotiation card"
- On selection, this option displays a dropdown list of all negotiation cards within the current context (namespace, model, version)
- When a particular card is selected, the content from this card is mapped into the current report fields
- These fields can then be edited further by the user

**Comment by sebastian-echeverria** [comment]
This is currently somehow achieved by the report by default including everything from the negotiation card.
