### ISSUE TITLE
Remove Explicit Types in Docstrings

### ISSUE THREAD

**Issue by turingcompl33t** [mlte-team/mlte#238]
Our previous documentation generator required explicit types in Python docstrings. Our new one does not. The new documentation generator reports warnings as a result of these redundant types. We should remove these explicit types from the docstrings.

**Comment by turingcompl33t** [comment]
@krmaffey assigning this to you if you have some cycles (likely ~1 hour) for this. You can use the documentation build system to check for all of the instances of this that we want to clean out.

**Comment by sebastian-echeverria** [comment]
Addressed by #388
