### ISSUE TITLE
Make Artifact Store URL in Frontend Configurable

### ISSUE THREAD

**Issue by turingcompl33t** [mlte-team/mlte#252]
Currently, the URL for the artifact store is hardcoded to a specific value in the frontend source. We should update this to make the value configurable.

In React applications I have written in the past, I determine this based on an environment variable that reflects whether the app is running in development or production. In development, we can continue to use a hardcoded value for the artifact store (say `http://localhost:8080`). In production, we must accept another parameter that contains the desired artifact store URL.

**Comment by sebastian-echeverria** [comment]
Continued in #405
