### ISSUE TITLE
Create Array Value type

### ISSUE THREAD

**Issue by sebastian-echeverria** [mlte-team/mlte#264]
A Value type of that implements an Array would be very useful as part of the base MLTE package. While using MLTE to create different conditions, we ended up creating an Array Value, and all other Values just derived from this one. Deriving from it also makes it easier to create new conditions, as only the validation methods have to be added for simple Values that can be stored as an array. There is an example in the feature/new-properties branch, demo-2/values/array_value.py

**Comment by krmaffey** [comment]
Partially addressed by PR #[306](https://github.com/mlte-team/mlte/pull/306), but ongoing conversation was moved to issue #323

**Comment by sebastian-echeverria** [comment]
Closing to avoiding having it duplicated. Work to be continued in #323
