### ISSUE TITLE
Use "force" Parameter to Update a Negotiation Card

### ISSUE THREAD

**Issue by turingcompl33t** [mlte-team/mlte#284]
The request to write an artifact accepts two additional parameters: `force` and `parents`. The `force` parameter can be used to solve one of the issues that @sei-aderr encountered when working on the UI: if the `force` parameter is specified, the negotiation card can be overwritten to effectively implement "update" semantics.

This is slightly tricky though because we don't want a user to be able to do the following:

- Create a new negotiation card
- Give it an ID that is equivalent to the ID for an existing card
- Overwrite an unrelated, existing card

Therefore, we will need to do some additional work in the frontend to ensure that the `force` parameter is only set to `true` when we are editing an existing card, and not when we are creating a new one.

**Comment by sei-aderr** [comment]
The way that I set up the check for whether it was an edit or not, is whether or not an artifactId is passed as a url parameter to the negotiation card page. 

In setup on line ~588 there is the check, `if(useRoute().query.artifactId !== undefined)` which checks if there is a artifact id in the url. If there is, it will load that negotiation card into the page.

If there is not one, there will be a text box on the screen, line ~55 allowing the user to enter an artifact ID for their card. This value will be saved as `userInputArtifactId` through its v-model.

```
<UsaTextInput v-if="useRoute().query.artifactId === undefined" v-model="userInputArifactId">
      <template #label>
        Artifact ID
        <InfoIcon>
          The Artifact ID this negotiation card <br />
          will be saved under upon submission.
        </InfoIcon>
      </template>
    </UsaTextInput>
```

What I think makes the most sense to implement this change, is in the `submit()` function, add a local parameter just like the identifier defined in the 5th line of function to save the T/F value of force. If the `if(useRoute().query.artifactId === undefined)` is true, it means that there is no artifactId in the url and we are making a new one so force should be false. If it is false, there is a url param, so we need to force to update the saved version so force is true.

Then just pass that T/F value as the force param in the body of the `useFetch` which is currently on line ~680. Then should be good to go

**Comment by krmaffey** [comment]
Made another issues for this then realized it already existed! My comment: "MLTE allows artifacts to be overridden using the force=True parameter. However, this is not implemented in the front end so users get an API error popup when trying to save a negotiation card over itself. The force parameter needs to be implemented in the front end, with some way for a user to confirm that they want to override their old version or save their negotiation card (or report) under a new name."

**Comment by sei-aderr** [comment]
Working on getting this implemented for the report and the negotiation card. 

How I currently have it set up is that if the user selects edit from the homepage, then force will be enabled on the submit of the form and it will save over the previous version.

 If they select new, there will be a field available at the top of the form to enter a name to be saved under. In this case, force will not be enabled so if there is a conflict it will not save. I can try and add a custom pop up for this case so it is more clear what the submission issue is. 

I will open a PR for the changes here in a second and you can try it out and see if it work as you would like or if you would like any changes to be made.
