### ISSUE TITLE
Refactor Main Artifact Store UI to Single-Select

### ISSUE THREAD

**Issue by turingcompl33t** [mlte-team/mlte#285]
Currently, we have (broken, I believe, according to @sei-aderr) support for multi-select of models and model versions on the main artifact store page. This is likely a result of mockups that did not perfectly reflect the intent for this page. We should refactor these to be single-select boxes (dropdowns) such that users may only select a single model and model version at a time. This should reflect the logic that is currently implemented anyway (users can currently only select a single model and version) and updates the UI to reflect this.

**Comment by sei-aderr** [comment]
So yes, the multi-select doesn't work properly at the moment as it isn't clear which model and version is selected to start a new negotiation card or report.

So like I saw you had started, the two divs that are `<div class="scrollable-div">` will be converted to `<UsaSelect>`. Then also as you were doing, you will want to have them call a method when they change. So on the `UsaSelect` page you can see that the event it emits is `update:modelValue`, so you will do something like this, `@update:modelValue=myMethod()`. With `myMethod` being `updateSelectedModels` and `updateSelectedVersions` which both will have to be updated slightly.

Then set the `v-model` of each select to be `selectedModel` and `selectedVersion` respectively to store those values.

(I think) Lastly the deleteVersion and deleteModel will have to be updated.

Typing this out makes me realize this may be a bit of a confusing change to make. If things become too unclear and painful to do, just let me know and I will get it implemented for you.
