### ISSUE TITLE
Change Report Render Button to "View"

### ISSUE THREAD

**Issue by turingcompl33t** [mlte-team/mlte#286]
Currently, we have an "Edit" button for report artifacts. Eventually, we will likely add support for report editing back in to the UI. For now, though, it is sufficient to be able to render a report and nothing else. Therefore, we should change the button to read "View" instead of "Edit".

**Comment by sei-aderr** [comment]
Change `Edit` to `View` on like 163 in `index.vue` and then each button in the report table will say view
