### ISSUE TITLE
Flatten Findings in Validated Specification

### ISSUE THREAD

**Issue by turingcompl33t** [mlte-team/mlte#287]
This issue is a discussion question.

Does it make sense to flatten the findings in a validated specification. Currently, they are organized by property. However, for rendering purposes, it might make more sense to organize them by individual "finding" and then push down the property information into each. This would require the introduction of a new (albeit simple) data structure.

**Comment by sei-aderr** [comment]
Could you give an example of what a validated spec currently looks like, and then what it would look like after these changes?

If you are looking to make this change just for rendering in the frontend, I probably wouldn't worry about it too much though. If the nesting makes it clearer when viewing it in the JSON, it shouldn't add really any complexity to the rendering of the page.

**Comment by sebastian-echeverria** [comment]
Not sure there is a need for this right now. Closing it for now at least.
