### ISSUE TITLE
Refactor Package Publication

### ISSUE THREAD

**Issue by turingcompl33t** [mlte-team/mlte#292]
Package publication is currently tedious an error-prone. We should improve the following:

- The multiple steps involved are not automated; building the UI and generating the package itself
- Currently, the Poetry build ignores the `.output` directory from the frontend build because this is ignored by `.gitignore`; figure out a way to get Poetry to include this anyway (the `tool.poetry.include` parameter doesn't seem to work)

**Comment by sebastian-echeverria** [comment]
This has already been addressed.
