### ISSUE TITLE
Integrate properties from scenarios demo into main mlte package

### ISSUE THREAD

**Issue by sebastian-echeverria** [mlte-team/mlte#297]
The scenarios demo added several properties: Robustness, Fairness, and a couple related to cpu and memory cost when predicting/inferring (as opposed to when training). Move this from the demo and integrate it into the main mlte properties package, since they are generic enough that they should be useful to most people.

**Comment by krmaffey** [comment]
Closed by PR#[306](https://github.com/mlte-team/mlte/pull/306)
