### ISSUE TITLE
Implement RDBMS Backend for Artifact Store

### ISSUE THREAD

**Issue by turingcompl33t** [mlte-team/mlte#298]
Currently, we have the following artifact store implementations:

- In-memory, which uses a naive, in-memory storage representation to store artifacts
- Filesystem, which uses the local filesystem to store artifacts
- Remote HTTP, which defers storage to a remote HTTP server

I'd like to introduce a new backend that uses a relational database management system for artifact storage. This should abstract over the underlying RDBMS that is used for storage by using an appropriate ORM, and allowing the user to specify the connection URI for the database directly.

**Comment by sebastian-echeverria** [comment]
Fixed in #360
