### ISSUE TITLE
Fix timestamp display in UI

### ISSUE THREAD

**Issue by sei-aderr** [mlte-team/mlte#361]
Kate - Hi Alex! Jenny looked at the UI and I'm going back over some of her comments/ideas. One thing that we are both seeing is that some of the timestamps are still wonky - when I created a negotiation card in the UI, I get the right date/time. However, a specification I created in code is giving a timestamp from 1970. Here are some screenshots!

**Comment by sebastian-echeverria** [comment]
Fixed by #363
