### ISSUE TITLE
Remove 'Identifiable Information' Field 

### ISSUE THREAD

**Issue by krmaffey** [mlte-team/mlte#365]
In the negotiation card, there is an extraneous field called 'identifiable information' that appears to have come from the tooltip for the Data Policies field. Data Policies should cover everything a team might need to address in terms of 'identifiable information', so we should not need that field to be separate. It can be removed from the negotiation card.

**Comment by sei-aderr** [comment]
Planning to address this along with the upcoming negotiation card changes

**Comment by sebastian-echeverria** [comment]
Agreed, that is a good moment to address this.

**Comment by sebastian-echeverria** [comment]
Addressed by #391
