### ISSUE TITLE
Implement Negotiation Card Changes in Front End

### ISSUE THREAD

**Issue by GALewis** [mlte-team/mlte#379]
Changes to the Negotiation Card need to be propagated to the Front End. Main changes are:

- New Fields for "Created by: User - Timestamp" and "Last Modified By: User - Timestamp"
- Section name changes
- All fields need to have an info button. For those that do not have one, copy text from TEC. Review attached document for details.
- All fields have an example that also needs to go with the info button.
- DATA: Order of fields changed
- DATA: Title for Labels is missing
- DATA: New field for "Labeling Method"
- DATA: New sub-field for Label called "Label Description"
- MODEL INFORMATION: Integration Field is replaced by two new fields: "Deployment Platform" and "Capability Deployment Mechanism"
- MODEL INFORMATION: "Input Specification" and "Output Specification" have sub-fields to provide structure.
- SYSTEM REQUIREMENTS is a new section that will contain an "array" of system qualities.

Details in attached document.

[MLTE Negotiation Card - Detailed Changes.docx](https://github.com/mlte-team/mlte/files/14827334/MLTE.Negotiation.Card.-.Detailed.Changes.docx)

**Comment by sei-aderr** [comment]
From Grace:
1. Make the save button always available at the bottom (Copy CSS from TEC)
2. Have a little paragraph that gets filled in as the user types up the system requireements

**Comment by sei-aderr** [comment]
Finished

**Comment by sebastian-echeverria** [comment]
Addressed by #391
