### ISSUE TITLE
Implement Negotiation Card Changes in Back End

### ISSUE THREAD

**Issue by GALewis** [mlte-team/mlte#380]
Changes to the Negotiation Card need to be propagated to the database. Main changes are:

- New fields for "Created by: User - Timestamp" and "Last Modified By: User - Timestamp"
- New field for "Labeling Method"
- New sub-field for Label called "Label Description"
- "Integration" field is replaced by two new fields: "Deployment Platform" and "Capability Deployment Mechanism"
- "Input Specification" and "Output Specification" have sub-fields to provide structure.
- System requirements is an "array" of system qualities with six sub-fields: "System Quality", "Stimulus", "Source of Stimulus", "Environment", "Response", and "Response Measure"

Details in attached document.

[MLTE Negotiation Card - Detailed Changes.docx](https://github.com/mlte-team/mlte/files/14827376/MLTE.Negotiation.Card.-.Detailed.Changes.docx)

**Comment by sebastian-echeverria** [comment]
Two things to consider:
 - Should we also make all these changes in the report? So far I have, except for the QAS (system requirements)
 - We should probably update the QAS demo with a negotiation card that has the QASs used in that demo+

**Comment by sebastian-echeverria** [comment]
Addressed by #391
