### ISSUE TITLE
Epic: Minor Refactoring and Improvements

### ISSUE THREAD

**Issue by sebastian-echeverria** [mlte-team/mlte#381]
This epic covers work on refactoring MLTE and making it more usable, as well as technical debt issues.

* #238 
* #302
* #292
* #215
* UI improvements to lessen fragility (need to add issue breakdown for this when ready)
* Display more artifacts in the UI (e.g., Specs and ValidatedSpecs for now; add issue when ready)
* Refactoring work to make the library easier to use (add issues)

**Comment by sei-aderr** [comment]
Closed for reprioritization in Continuum.
