### ISSUE TITLE
Consistent Error Handling for Frontend

### ISSUE THREAD

**Issue by sei-aderr** [mlte-team/mlte#387]
Find some way to make API calls happen in methods that can be abstracted out and used to handle errors consistently throughout the frontend. 

From Sebastian current error - 
`In terms of error, I was seeing it with disabled users. If a user gets a token, then I disable that user (myself maybe), and then I try to get a page, it will return a 403 Forbidden error. But the frontend does not seem to be checking for those errors, or checking that it is getting a 200 response, as it will gladly show me a page (say, the users page), but empty, instead of indicating that I was not allowed to access that page. This will happen more often once we work with permissions, since besides the disabled user case, because of roles there would be other causes for a 403 Forbidden error when accessing the API resources. But besides maybe handling the 403 Forbidden error in a specific way, we should also handle any unknown, non 200 HTTP response error in the frontend, in some standard way.`

**Comment by sebastian-echeverria** [comment]
Addressed in #434
