### ISSUE TITLE
MLTE Evaluation Survey

### ISSUE THREAD

**Issue by GALewis** [mlte-team/mlte#395]
Turn the evaluation metrics into a Google Forms survey.

**Comment by GALewis** [comment]
@rbedman Is going to add N/A as an answer to each question.

**Comment by GALewis** [comment]
How about something like this?

![Image](https://github.com/mlte-team/mlte/assets/3449598/03524d7f-5792-4dae-9170-710612ef0915)

**Comment by rbedman** [comment]
So you are suggesting a multiple choice grid? So something like this?

**Comment by GALewis** [comment]
I am OK with that
