### ISSUE TITLE
MLTE Evaluation Protocol

### ISSUE THREAD

**Issue by GALewis** [mlte-team/mlte#396]
The MLTE Evaluation protocol is the process for MLTE evaluation and should consider

- Determining when and how to administer the pre and post surveys
- Training on MLTE goals and how to use MLTE
- Coaching thorough using the MLTE process

**Comment by krmaffey** [comment]
Here is a first draft of the evaluation protocol - below in markdown, and [attached](https://github.com/mlte-team/mlte/files/15337552/MLTE_Eval_Protocol_v1.docx) in a Word document. Looking forward to comments and changes!

# MLTE Evaluation Protocol
Draft 16 May 2024

## Step 1: Project Familiarization
- Participants need time to become acquainted with their projects.
- This will vary by project and team; for participants who are completely new to a project, one week of familiarization is recommended before MLTE is introduced.

## Step 2: Initial Survey
- Once participants have onboarded and familiarized themselves with their projects, the MLTE team should have them fill out the survey.

## Step 3: MLTE Introduction
- The MLTE team gives participants an introduction to MLTE, focusing on the process. 
- This will likely require a ~1 hour meeting including the following content
    - MLTE overview
    - Negotiation card demonstration
    - Time for questions/interaction with participants
- Prior to this meeting, the team should set up a central location where negotiation cards can be saved and viewed by all participants and the stakeholders.

## Step 4: Project Progression
- This step does not involve the MLTE team; participants need time to work on their projects at their own pace. Likely ~2-3 weeks.

## (OPTIONAL) Step 5: Testing with MLTE
- If a project progresses to the point where it has a functioning model that can be tested, the MLTE team should schedule with the participant for a demonstration of MLTE testing capabilities. 
- This likely will involve another ~1 hour meeting in which the team conducts an overview and then demonstration of MLTE test capabilities, then a hands-on portion with time to answer questions and help participants as needed.

## Step 6: Final Survey
- At the end of the project or after ~1 month of work on it (whichever comes first), the MLTE team should have participants take the survey again.

**Comment by GALewis** [comment]
Comments attached.

[MLTE_Eval_Protocol_v1-glewis.docx](https://github.com/mlte-team/mlte/files/15349229/MLTE_Eval_Protocol_v1-glewis.docx)

**Comment by krmaffey** [comment]
Updated! Jenny couldn't comment here but she also gave me some edits and I've included those as well.

[MLTE_Eval_Protocol_v2.docx](https://github.com/mlte-team/mlte/files/15394327/MLTE_Eval_Protocol_v2.docx)

**Comment by GALewis** [comment]
I just have some minor comments. I think we are good to go!



[MLTE_Eval_Protocol_v2-glewis.docx](https://github.com/mlte-team/mlte/files/15405233/MLTE_Eval_Protocol_v2-glewis.docx)

**Comment by krmaffey** [comment]
[MLTE_Eval_Protocol_May_2024.docx](https://github.com/mlte-team/mlte/files/15421976/MLTE_Eval_Protocol_May_2024.docx)
[MLTE_Eval_Protocol_May_2024.pdf](https://github.com/mlte-team/mlte/files/15421977/MLTE_Eval_Protocol_May_2024.pdf)

# MLTE Evaluation Protocol
23 May 2024

## Step 1: Project Familiarization
- Participants need time to become acquainted with their projects.
- This will vary by project and team. We recommend that participants have access to the code base, familiarization with the project goals, and an understanding of data sources before MLTE is introduced (generally one week of familiarization).

## Step 2: Initial Survey
- Once participants have onboarded and familiarized themselves with their projects, the MLTE team will ask participants to fill out the survey.

## Step 3: MLTE Introduction
- The MLTE team gives participants an introduction to MLTE, focusing on the process. 
- This will likely require a ~1 hour meeting including the following content:
    - MLTE overview
    - Negotiation card demonstration
    - Time for questions/interaction with participants
- Prior to this meeting, the team will set up a central location where negotiation cards can be saved and viewed by all participants and the stakeholders.

## Step 4: Project Progression
- Participants need time to work on their projects at their own pace. Likely ~2-3 weeks, with weekly check-in meetings between the MLTE team and developers, and between the MLTE team and product/project owners, to understand how MLTE is being used and provide coaching as needed.

## (OPTIONAL) Step 5: Testing with MLTE
- If a project progresses to the point where it has a functioning model that can be tested, the MLTE team will schedule a meeting with the participant for a demonstration of MLTE testing capabilities.
- This will involve another ~1 hour meeting in which the team conducts an overview and demonstration of MLTE test capabilities, with a hands-on portion with time to answer questions and help participants as needed.

## Step 6: Final Survey
- At the end of the project or after ~1 month of work on it (whichever comes first), the MLTE team will ask participants to take the survey again.
