### ISSUE TITLE
Make report export show up in new tab

### ISSUE THREAD

**Issue by sei-aderr** [mlte-team/mlte#416]
From Sebastian,

"Btw, I know this is not something you are expliciting working on, but I was looking at the Rerpot Export functionality, and even though it looks good, I think it may be a good idea to open that exported Report page in a new tab, instead of the same one. You lose navigation other than the browser buttons in that case, and opening a print version in a separate tab is a behavior I've seen around, including in Gmail."

**Comment by sebastian-echeverria** [comment]
Addressed in #434
