### ISSUE TITLE
Standardize use of breadcrumb in frontend

### ISSUE THREAD

**Issue by sei-aderr** [mlte-team/mlte#422]
Navigation not super clear at the moment, some original pages have breadcrumb but hasn't made it to all pages

**Comment by sei-aderr** [comment]
@sebastian-echeverria 

Breadcrumb is a UI component to show the path you are at in the UI. https://designsystem.digital.gov/components/breadcrumb/

The structure is pretty flat at the moment, so may not be super useful. Let me know what you think after the other navigation updates I made.

**Comment by sebastian-echeverria** [comment]
Looking at the current status and the current changes, I agree, I don't think this UI component would be very useful, for now. If the structure gets more complex, it could help out, but as I see it now, the navigation bar propvides plenty of cues of where we are, and I don't see what this would add other than redundancy.

**Comment by sei-aderr** [comment]
Agreed. Can reconsider later if it starts to get confusing again. Thanks
