### ISSUE TITLE
Frontend Navigation Improvements

### ISSUE THREAD

**Issue by sebastian-echeverria** [mlte-team/mlte#432]
Currently there is no clear way to go back to the main models/artifacts page once you are managing users, groups, or editing your own profile. If you click on the main MLTE icon it takes you there, which is fine, but there should also be a more explicit way to get to the main page. One way would be to add a button next to the Logout one, called Models, that also leads to the models page.

It would also be nice to have a better way to indicate where you are. When going to Manage Users, for example, it doesn't highlight that button, or show a title, or otherwise show me where I am. I can figure that out only by remembering how I got there and the context of the data inside. It would be nice to have a clearer way to show it. The easiest solution would be to highlight the button that you clicked that is associated to where you are; for example, highlight the "Models" button in the main page, or the "Manage Users" button on that page. 

Also having a title in the browser tab saying something like "MLTE - Manage Users" depending on where you are would be useful.

**Comment by sei-aderr** [comment]
I just added several pieces of this so please check them out and see if they make sense.

The breadcrumb, aka the "path" to the page is still coming in a separate task, as well as the manage users/group page redirecting back to the list of users/groups when in the edit page.

**Comment by sebastian-echeverria** [comment]
The navigation bar on the left looks very good, and works great to show you where you are and to allow for easy navigation. A couple of minor comments:
 - I like the fact that the page title in the browser tab changes along with the page you are, thanks! The only change I would make is to add a prefix to it... e.g., instead of the pages' titles being "Artifact Store", "Test Catalog", I'd make them "MLTE - Artifact Store", "MLTE - Test Catalog". When you have a lot of tabs, it is useful for them to give you the overall context of the site you are in. 

Some other, non-navigation comments about things I noticed:
 - The New Catalog Entry button behaves very much like the Add User and Add Group buttons, but it has two structural differences: 1) it is called New Catalog Entry instead of "Add Catalog Entry", and 2) unlike the Add User and Add Group buttons, it is not located underneath the Logout button, but in a right column. I would try moving it to the same location the Add User and Add Group buttons are, and rename it to Add Catalog Entry for consistency. As a side comment, I know that the way to create Models and Versions is different, but they are structurally different (they don't lead to a new page to fill out things, they are not the main resource being displayed, etc), so it may be ok for those two to remain as they are.
 - The Edit Profile page for when a user edits its own profile is missing its title, both in the browser tab as well as at the top of the page, which also leads to a weird artifact with the separator line being on top of the Logout button.

**Comment by sei-aderr** [comment]
I disagree on the first point. From memory and looking through several tabs I have open, I feel that the  icon of a website provides the context of which site you are in, and then the title tells you which page on that site you are on. It feels redundant to me to have the MLTE icon, and then specify that you are on the MLTE page.

Yes, good catch on the inconsistencies with the button. I mean to move the button and missed that one, and didn't realize the name wasn't consistent. 

Added the titles and moved the button on. edit profile to be consistent.

**Comment by sebastian-echeverria** [comment]
All changes look good, thanks.

A very, very minor thing: is it possible for the "Admin Pages" and "User Pages" entry in the left side menu to be not selectable? Right now they work just as a grouping to put other actual pages underneath, but they still act as clickable and can be clicked, and then nothing happens (since they are just a group name). If it was possible to make them non-clickable, it would be more consistent with what they are. If it is too hard, it is not really that critical.

**Comment by sei-aderr** [comment]
Actually just found a workaround for having it not highlight on hover. You can add this line to `nuxt-app/layouts/base-layout` line 46 instead of the <a> tag and compare what the two look like. I think no highlight makes more sense because it ins't a link in any way

`<div style="padding: .5rem 1rem; display: block; color: #565c65">Admin Pages</div>`

**Comment by sebastian-echeverria** [comment]
Looks great, thanks!

**Comment by sebastian-echeverria** [comment]
Closed in #478
