### ISSUE TITLE
Create Negotiation Card Instructions

### ISSUE THREAD

**Issue by krmaffey** [mlte-team/mlte#442]
Write up instructions for the negotiation card that make clear that you don’t have to do it all at once and that the order can be based on your team’s needs, rather than the order of the form.

**Comment by krmaffey** [comment]
**Previous Negotiation Card instructions:**
Teams should work through as many of the following items before starting model development. The Negotiation Card can and should be revisited at any negotiation point. Teams should refer to this Negotiation Card during development to ensure they capture all relevant critical aspects of the model and system. Hover over the black information icons next to each field to get more information about that field. Click on the Example button to see specific examples for a section.

**Proposed new Negotiation Card instructions:**
Teams should use the negotiation card to guide an in-depth discussion for project scoping. The card can be completed in any order and the idea is that teams fill out as much as they can at the beginning of the project process and revisit the card throughout as the project matures. There are five sections in the Negotiation Card:
- System Information
- Data
- Model Information
- System Requirements

Negotiation Cards serve as a critical reference for teams throughout development even when they are partially filled out. Hover over the black information icons next to each field to get more information about that field. Click on the Example button to see specific examples for a section.

----------

@GALewis and @JennyNiemann, what do you think of the above proposed changes to the Negotiation Card instructions? For now we can just add these and then at a later time we could add links to the section list so people can navigate directly to them?

**Comment by GALewis** [comment]
I think it looks good. The only comment is that there are four sections and not five?

**Comment by krmaffey** [comment]
Great point Grace - no idea why I thought there were five. I'll make that change and update the description in a PR, thank you!
