### ISSUE TITLE
Ensure consistency between docs and Jupyter Notebook demos

### ISSUE THREAD

**Issue by sebastian-echeverria** [mlte-team/mlte#461]
The MLTE documentation uses some examples that may be outdated in comparison to code in the Jupyter Notebook demos, and in some cases may be using parts of one demo or the other, which can be confusing. Review and ensure it is consistent.

**Comment by rbedman** [comment]
Academic Lit papers to include:
- [Habibullah 2022]
- [Habibullah 2023] 
- [Li 2023]
- [Nakamichi 2020]
- [Pons 2019]

And grey-lit
- [Kästner 2022]

**Comment by rbedman** [comment]
Real issue here was iris vs oxford dataset in the notebooks and the sample data store. Should be all in terms of oxford. Not sure if there are other refs to iris in the docs.

**Comment by rbedman** [comment]
@krmaffey offered to review the external facing documents.

**Comment by krmaffey** [comment]
External-facing documentation has been reviewed, and I submitted a pull request (#503) with a few changes where it was referencing the wrong dataset (Iris vs. Oxford) and using outdated code. Let me know if you want me to look at the internal docs next, I can create a different issue for that if we want!

**Comment by sebastian-echeverria** [comment]
Properly addressed by #503
