### ISSUE TITLE
Epic: Changes to Relationship between Negotiation Card and Report

### ISSUE THREAD

**Issue by sebastian-echeverria** [mlte-team/mlte#468]
This epic refers to changes into how the Negotiation Card and Report are related, especially in terms of how static the report should be, and pending things when handling common data between them.

* #465 
* #456 
* #451
* #463
* #357 
* #231 (note that this is outdated and likely will need to be changed)

**Comment by sei-aderr** [comment]
Closed for reprioritization in Continuum.
