### ISSUE TITLE
Add Mechanism for "Discussion" Measurements

### ISSUE THREAD

**Issue by turingcompl33t** [mlte-team/mlte#54]
Sometimes, it will not make sense to provide a "quantitative" measurement + validation for a property in the form of executable code. To address this need, we should provide pseudo-measurements that essentially allow users to attach arbitrary "data artifacts" to a property as a means of attesting to its evaluation. Examples might include:
- `TextualEvidence`: allow the user to embed an arbitrary textual discussion in the report.
- `VisualEvidence`: allow the user to embed an arbitrary graphic in the report.

I am open for a discussion on the names of these measurements.

These will require extensions to support measurements in the report that do not have attached validators.

**Comment by sebastian-echeverria** [comment]
This seems to be at least partially supported now, with the "Ignore" result type. There will be work to improve that anyway, but for now this will be closed, at least as it is described.
