### ISSUE TITLE
Create a script for MLTE presentation demo

### ISSUE THREAD

**Issue by sei-secheverria** [mlte-team/mlte#544]
Create an overall script for how the demo will go.

**Comment by sei-secheverria** [comment]
A rough script follows:

Pre requirements:
 - Have environment running (see #546)
 - Have already executed all notebooks that will be shown, so the results can be seen in the notebooks themselves.

Demo:
 - Start with slides explaining what MLTE is
 - Continue slides including a good diagram of the whole process. Use this diagram later with more slides to indicate where in the process we are as we move forward through the demo
 - Log into frontend, show Negotiation Card. Explain important parts of negotiation card and how it is refined
 - Open up Jupyter Notebook with Spec (the one in demo/scenarios/1_requirements.ipynb. Note that we may need a slightly modified version if we add a data quality QAS. Skip the Negotiation Card definition, but do show the context initialization, and then the Spec definition. Walk though it without getting into too many details
 - Go back to frontend. Show Test Catalog, and show how people would use it find an example of how to measure certain QAS.
 - Open up one or two Jupyter Notebooks with QAS test measurements. Probably one existing one, and maybe the data quality one if it gets added (see #547) Walk though each notebook.
 - Open up the demo/scenarios/3_report.ipynb Notebook, and show the process for validating and generating the report.
 - Go back to frontend, and show the report results.

**Comment by sei-secheverria** [comment]
@rbedman @sei-glewis in the comment above I have a rough script of the demo. Please take a look at it and let me know what you think.

**Comment by sei-glewis** [comment]
This works for me. Thank you. Would like  to do a couple of runs through it before the 16th. Will likely use for a meeting in January with DTE&A as well.
