### ISSUE TITLE
Create slides to use alongside the MLTE presentation demo

### ISSUE THREAD

**Issue by sei-secheverria** [mlte-team/mlte#545]
Based on #544, create slides for the presentation demo.

**Comment by sei-glewis** [comment]
@sei-secheverria and @rbedman, the attached slides are ready for review. My plan is to set the context with Slides 3, 4 and 5, and then hand it over to Sebastián to use slides 6 and 7 as needed. Do we need to add any more slides?

[20241216 - AFTC - MLTE Demo.pptx](https://github.com/user-attachments/files/18029383/20241216.-.AFTC.-.MLTE.Demo.pptx)

**Comment by sei-secheverria** [comment]
Given the script in #544, these slides are probably enough. Thanks!

**Comment by sei-glewis** [comment]
I added the slide that Rachel created. Let me know if that works.

[20241216 - AFTC - MLTE Demo.pptx](https://github.com/user-attachments/files/18113278/20241216.-.AFTC.-.MLTE.Demo.pptx)

**Comment by sei-secheverria** [comment]
Thanks!
