### ISSUE TITLE
Rename "Artifact Store" to "Evidence Store"

### ISSUE THREAD

**Issue by turingcompl33t** [mlte-team/mlte#73]
We currently use the term "artifact store" to refer to the component that stores serialized `Result`s. However, perhaps "artifact" is an unnecessarily -imprecise term for the things that we intend to store. Should we change the name to something else that is more descriptive, like "Evidence Store"?

**Comment by turingcompl33t** [comment]
Will need input from @krmaffey and @JennyNiemann on this one.

**Comment by krmaffey** [comment]
I like evidence store better! Especially since it's more consistent with what we say in the paper in terms of collecting evidence against requirements. The only question I have then is maybe we should call results 'evidence' instead? Or maybe that's too much. We can discuss further

**Comment by turingcompl33t** [comment]
Closing this one. "Artifact Store" is the appropriate name because it stores more than just evidence now.
