### ISSUE TITLE
Fill Out `BoundSpec` Functionality

### ISSUE THREAD

**Issue by turingcompl33t** [mlte-team/mlte#95]
Currently, `BoundSpec` is just a simple wrapper around the document produced by the process of binding results to properties within a specification. However, we should be able to interact with `BoundSpec` the same way we do with all other types within the hierarchy.

**Comment by sebastian-echeverria** [comment]
PR #146 ended up possibly addressing this, since now ValidatedSpec (formerly BoundSpec) contains a Spec and a list of Results, and has to/from json functions, unlike its previous implementation.

**Comment by turingcompl33t** [comment]
Closed by #146,
